language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - composer install

script:
  - ./vendor/bin/phpunit tests

notifications:
  email:
    - ddelrio1986@gmail.com
    - daniel@aelearn.com